# Generated by Django 3.2.4 on 2021-06-03 16:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('url', models.CharField(max_length=1000)),
                ('website_name', models.CharField(max_length=20)),
                ('image_url', models.CharField(blank=True, max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('counter', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
